repository: ../neo-sophia
extensions: ['.py']
db_path: .database/
cache_dir: .cache/
Tools:
  - module: groundcrew.tools
    tools:
      - CodebaseQATool
      - SingleDocstringTool
      - LintFileTool
      - CyclomaticComplexityTool
      - FindUsageTool
colorscheme: 'gruvbox-dark'
debug: true
