repository: ../groundcrew
extensions: ['.py', '.txt', '.yaml', '.yml', '.sh', '.md', '.toml']
db_path: .groundcrew_openai_database/
cache_dir: .groundcrew_openai_cache/
Tools:
  - module: groundcrew.tools
    tools:
      - CodebaseQATool
      - SingleDocstringTool
      - LintFileTool
      - GetFileContentsTool
      - CyclomaticComplexityTool
      - FindUsageTool
      - InstallationAndUseTool
colorscheme: 'gruvbox-dark'
debug: true
model: 'gpt-4-1106-preview'
llm_module: 'groundcrew.llm.openaiapi'